library(tidyverse)
library(here)
library(janitor)
library(arsenal)
library(lubridate)
library(dplyr)
fav_desserts <- read_csv(here("favorite_desserts.csv")) %in% clean_names()
iconic_desserts <- read_csv(here("iconic_desserts.csv"))

comparedf(fav_desserts, iconic_desserts)
library(arsenal)
library("janitor")
library("arsenal")
library(janitor)
fav_rename <- fav_desserts |>
  rename(dessert = Favorite_dessert)
compare <- comparedf(fav_rename, iconic_desserts)
des <- intersect(name(fav_rename), name(iconic_desserts))
inner <- inner_join(fav_rename, iconic_desserts)
clean_fav <- iconic_desserts |> mutate(des = tolower(iconic_desserts$dessert))
inner <- inner_join(fav_rename, clean_fav)
left <- left_join(fav_rename, clean_fav)
is_dessert <- str_detect(clean_fav, pattern = "cheesecake")
